# Generated by Django 3.1.5 on 2021-01-14 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20210114_2220'),
        ('product', '0006_auto_20210114_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PROvariant',
        ),
        migrations.AlterField(
            model_name='product',
            name='PRObrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.brand', verbose_name='Product Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PROcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category'),
        ),
    ]
