# Generated by Django 3.1.5 on 2021-01-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_proimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRO',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
