# Generated by Django 3.1.5 on 2021-01-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_prodisprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRObestsaler',
            field=models.BooleanField(default=False, verbose_name='Best Saler'),
        ),
        migrations.AddField(
            model_name='product',
            name='PROnew',
            field=models.BooleanField(default=True, verbose_name='NEW'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PROslug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
