# Generated by Django 3.1.5 on 2021-01-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210127_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CATslug',
            field=models.SlugField(blank=True, null=True, verbose_name='Category slug'),
        ),
    ]
