# Generated by Django 3.1.5 on 2021-02-01 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_category_catslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PROcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procategory', to='product.category', verbose_name='Category'),
        ),
    ]
