# Generated by Django 3.1.5 on 2021-02-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210201_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PROcost',
            field=models.FloatField(verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PROdisprice',
            field=models.FloatField(verbose_name='Discount Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PROimage',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PROname',
            field=models.CharField(max_length=255, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PROprice',
            field=models.FloatField(verbose_name='Price'),
        ),
    ]
