# Generated by Django 3.1.5 on 2021-02-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='addres',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
    ]
