# Generated by Django 3.1.5 on 2021-01-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='BRdesc',
            field=models.TextField(blank=True, null=True, verbose_name='Brand description'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='BRname',
            field=models.CharField(max_length=40, verbose_name='Brand name'),
        ),
    ]
